add_newline = false

[battery]
disabled = true

[character]
success_symbol = "[«\\(\\(\\(^❯](red bold)"

[directory]
fish_style_pwd_dir_length = 0
truncation_length = 0

[git_branch]
format = "on [$symbol$branch](#f1fa8c) "

[line_break]
disabled = true

[package]
disabled = true


[python]
#disabled = true
symbol = " "
